### ISSUE TITLE
Consume only mode

### ISSUE THREAD

**Issue by borkabu** [Amerousful/gatling-kafka#5]
Hi

As I understand there are currently only two ways to use this plugin: fire&forget and request&reply
I wonder if it is possible to use this plugin for consuming messages only?
My workflow is following:
1. Gatling sends messages to Rest service
2. Message goes through a chain of services and ends up in Kafka topic
3. Gatling consumes that topic, matches messages, etc

Thank you.

**Comment by Amerousful** [comment]
Hey!)

It's a promising concept, but currently, the implementation seems somewhat unclear to me. I'm particularly concerned about the matching process because, in this scenario, we also need to pass the payload in the same manner as for request-reply logic.
However, clear and meaningful notes about it in the documentation could help.


```scala
val kafkaOnlyConsume = kafka("Kafka: only consume")
  .onlyConsume
  .readTopic("input_topic")
  .payload("""{ "m": "#{payload}" }""")                <---- ONLY for matching
  .key("#{id} #{key}")                                              <---- ONLY for matching
  .check(jsonPath("$.m").is("#{payload}_1"))
  ```
***
One more useless thing I would like to implement for this realization is elapsed time on consuming, for statistics:
-- Send HTTP request
-- Write the start point into `Session`
-- Consume a message from Kafka
 ```scala
 val kafkaOnlyConsume = kafka("Kafka: only consume")
  .onlyConsume
  .readTopic("input_topic")
  .startPoint("#{currentTimeMillis()}")
  ...
  ```
 
 How does it look for you? Perhaps you have some suggestions and ideas about everything that I wrote above?

**Comment by borkabu** [comment]
Hi

Thank you for looking into that. 

I normally would match message by messageId, which I know in advance and which would be extracted in a certain predictable way from resulting kafka message (for example, currently I am using regexp to parse kafka message to extract messageId). I guess that is the answer for how payload could work. I also imagine that there might be use cases when it would be impossible to match by payload, so that should be optional. 

Second point is spot on. This is how I am expecting to use it, measure away time for each message and log it into stats engine.

**Comment by Amerousful** [comment]
@borkabu Hello!)
 Would you mind taking a quick look to ensure that the new functionality is working as you expected? Your help would be greatly appreciated!

[Documentation](https://github.com/Amerousful/gatling-kafka/blob/version_3.0/README.md)
[Pull request ](https://github.com/Amerousful/gatling-kafka/pull/7)

**Comment by Amerousful** [comment]
Thanks!)

It hasn't been published yet) 
Waiting this https://github.com/Amerousful/gatling-kafka/issues/4

**Comment by Amerousful** [comment]
The new version was published. Feel free to write here if a new version has some problems or bugs.
